Feature/login using facebook
oclockvn/megax pull request #7
Opened 2023-05-23 16:12 UTC by tungbinhdinh89

setup login page and interaction

2023-05-24 01:23 UTC, tungbinhdinh89 commented
[https://youtu.be/E3O94KcO3ak](url)

2023-05-24 14:06 UTC, oclockvn requested changes

2023-05-24 14:06 UTC, oclockvn commented on src/megax/MegaApp/Vite/src/pages/Login/LoginPage.tsx
> +            console.log(values);
remove console log

2023-05-24 14:06 UTC, oclockvn commented on src/megax/MegaApp/Vite/src/pages/Login/LoginPage.tsx
> +                required: "Thi is required.",
```suggestion
                required: "Username is required.",
```

2023-05-24 14:06 UTC, oclockvn commented on src/megax/MegaApp/Vite/src/pages/Login/LoginPage.tsx
> +                required: "Thi is required.",
```suggestion
                required: "Password is required.",
```

2023-05-24 15:27 UTC, tungbinhdinh89 commented on src/megax/MegaApp/Vite/src/App.tsx
> +// import reactLogo from './assets/react.svg'
yes, oke, i remember.

2023-05-25 02:03 UTC, oclockvn approved these changes

2023-05-25 02:29 UTC, merged